### ISSUE TITLE
Buttons being displayed even without the required permissions

### ISSUE THREAD

**Issue by dav1312** [official-stockfish/fishtest#1233]
A user who is not logged in or that it doesn't have the required permissions to perform a certaint action shouldn't even be able to see (in my opinion) certain action buttons such as "Stop", "Approve", "Reschedule", "Modify", etc.

This would apply to some inputs too like priority or throughput.

Or at least instead of hiding them, adding the disabled attribute to them would be nice.

**Comment by vdbergh** [comment]
In principle you are right but in my experience making such a thing robust requires some care. The typical case to watch out for is this: the user goes to the test page, then goes to the login page, logs in and uses the back button to go back to the test page. Now the buttons have to be adjusted. But the browser will not reload the page by itself.

So we need some JavaScript to query the login status of the user (I am not sure how the login works, cookie?).

**Comment by vdbergh** [comment]
Yes logging in sets a cookie. So this is a pure JavaScript issue.

**Comment by joergoster** [comment]
Maybe related, I no longer see if my test has been approved or not. Is this intentional?

**Comment by ppigazzini** [comment]
This PR dropped the "question mark" and "thumb up" icons, tests are divided in proper sections, in home page and user page

![image](https://user-images.githubusercontent.com/15718418/149634580-5d883153-13a0-4c63-911c-1b1a52ae4170.png)


![image](https://user-images.githubusercontent.com/15718418/149634626-db8a953d-f344-4e7f-9533-c110457fd3c3.png)

**Comment by vdbergh** [comment]
I think this meanwhile fixed. Can be closed.
