### ISSUE TITLE
Fixed font for the number columns in the user statistics

### ISSUE THREAD

**Issue by JojoM-sf** [official-stockfish/fishtest#1542]
A very minor issue indeed. Would it be possible to realize a fixed font for the numbers shown on the user statistics webpage? It would make the page much more legible, I think.

**Comment by peregrineshahin** [comment]
> A very minor issue indeed. Would it be possible to realize a fixed font for the numbers shown on the user statistics webpage? It would make the page much more legible, I think.

I'm unsure I can understand the discrepancy you're seeing regarding font on that page.
Could you please provide a screenshot?

**Comment by dav1312** [comment]
I think that by "fixed" font they mean a monospace font

**Comment by vdbergh** [comment]
Probably fixed by now. Can be closed.

**Comment by vondele** [comment]
I think it is fixed, looks also pretty good right now.
