### ISSUE TITLE
assertion triggered during fleet run

### ISSUE THREAD

**Issue by vondele** [official-stockfish/fishtest#1641]
https://tests.stockfishchess.org/actions?max_actions=1&action=&user=&text=Exception+AssertionError&before=1682701341.634387&run_id=

https://github.com/glinscott/fishtest/blob/6be811d340d87e0430d63af73a8daf50ca490b1d/worker/games.py#L1329 

currently triggered 4 times.

**Comment by vdbergh** [comment]
![Screenshot from 2023-04-28 20-32-37](https://user-images.githubusercontent.com/6613103/235226411-902429fb-6266-4c53-b92f-93bb48c16747.png)

There seems to be an error with quantization (170 is not divisible by 8, let alone 32).

**Comment by vondele** [comment]
current batch size is not 8 or 32 (has been adjusted).

**Comment by vdbergh** [comment]
Ok it seems the batch size is 6 games (obtained via /api/get_run). 170 is still not divisible by 6.

**Comment by vdbergh** [comment]
Not relevant for this issue, but I think currently the maximum number of games must be a multiple of the sprt batch size. This should be fixed.

**Comment by vdbergh** [comment]
Ok this last comment seems to explain it somehow as `(800000-170)%6=0`. But one would expect left over games to be assigned in the last task which is not the case here (assigning tasks is done under lock so normally there should be no race).

**Comment by vdbergh** [comment]
Ah I see it. Left over games are assigned on the basis of "finished tasks" and "committed games" (computed using the active tasks). Of course the committed games may not actually be realized if the task finishes prematurely. In that case new tasks have to be created, which happened here.

**Comment by vondele** [comment]
yes:
```
Apr 28 16:45:31 tests pserve[19713]: Failed_task: failure for: https://tests.stockfishchess.org/tests/view/644bc67ff609e0c9f1576d5b, task_id: 2569, worker: ChessDBCN-8cores-b62b6351-8bd9, reason: 'Exception AssertionError at games.py:1329'
Apr 28 16:46:31 tests pserve[19713]: Failed_task: failure for: https://tests.stockfishchess.org/tests/view/644bc67ff609e0c9f1576d5b, task_id: 2570, worker: ChessDBCN-8cores-c0c0235b-0c82, reason: 'Exception AssertionError at games.py:1329'
Apr 28 16:48:31 tests pserve[19713]: Failed_task: failure for: https://tests.stockfishchess.org/tests/view/644bc67ff609e0c9f1576d5b, task_id: 2572, worker: ChessDBCN-8cores-92bf66e8-d948, reason: 'Exception AssertionError at games.py:1329'
Apr 28 17:02:21 tests pserve[19713]: Failed_task: failure for: https://tests.stockfishchess.org/tests/view/644baff8f609e0c9f1576b8b, task_id: 2513, worker: ChessDBCN-8cores-50a0b09a-6fc8, reason: 'Exception AssertionError at games.py:1329'
```

**Comment by vdbergh** [comment]
From this issue we see another problem. Far too many workers are assigned to a run when the fleet arrives since the code assumes that an sprt test will really take 800000 games while most sprt tests only take around 200000 games.

**Comment by vdbergh** [comment]
This can be closed. It was fixed.
