### ISSUE TITLE
/api/active_runs still returns a large amount data

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#1678]
```sh
woolf@pl2:~$ wget tests.stockfishchess.org/api/active_runs
URL transformed to HTTPS due to an HSTS policy
--2023-05-09 15:26:25--  https://tests.stockfishchess.org/api/active_runs
Resolving tests.stockfishchess.org (tests.stockfishchess.org)... 185.83.217.134
Connecting to tests.stockfishchess.org (tests.stockfishchess.org)|185.83.217.134|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 212373 (207K) [application/json]
Saving to: ‘active_runs.21’

active_runs      100%[===================>] 207,40K  --.-KB/s    in 0,1s    

2023-05-09 15:26:26 (1,61 MB/s) - ‘active_runs.21’ saved [212373/212373]
```
The reason is the SPSA data, which I am actually not interested in (and I think the same holds for other users). It would be a good idea to provide the api with an optional argument to omit the SPSA data. Or even an additional projection argument.

**Comment by vondele** [comment]
The SPSA history is removed, the actual spsa data provided is the 'summary data'.

**Comment by vdbergh** [comment]
Yes but it is till a lot of data (207K in the above example).

**Comment by vdbergh** [comment]
But regardless of this, an additional projection argument would be useful.

**Comment by vdbergh** [comment]
I thought post requests are not generally cached... I think you can force the server to cache them, but the expectation is that they are not.
