### ISSUE TITLE
Retire the min_threads option?

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#1723]
Setting this to > 1 guarantees that you will almost never get any tasks. So you may as well not run a worker.

**Comment by vondele** [comment]
I think historically this was added to have a worker pick a specific task that ran with very high concurrency. I.e. not waste a 32 thread worker on 1 thread STC, when there is a 32 thread task pending.

It is not overly important to have this option, but I don't mind having it.
