### ISSUE TITLE
What would be a good UI for blocking/unblocking workers?

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#1774]
The blocking must happen on the basis of username+uuid_prefix, but other than that I have no inspiration for a convenient user interface.

**Comment by vdbergh** [comment]
One idea would be to make the worker names in the event log into links. The link would go to a page that allows for blocking/unblocking that name. Of course this functionality should only be accessible to approvers.

**Comment by vdbergh** [comment]
Ok I started hacking something. I will have something by tomorrow I hope.

**Comment by ppigazzini** [comment]
23:35:00 left to the deadline....

**Comment by vdbergh** [comment]
Fixed by #1777 and further PRs.
