### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by vondele** [official-stockfish/fishtest#1801]
calling 

https://tests.stockfishchess.org/api/pgn_100/64fd90925dab775b5359f984 

leads to an internal server error. 

Trying to figure out how to use our api_download_pgn_100 route..

**Comment by ppigazzini** [comment]
```yaml
Sep 10 13:30:25 tests.stockfishchess.org pserve[3612]:   File "/home/fishtest/fishtest/server/fishtest/api.py", line 496, in download_pgn_100
Sep 10 13:30:25 tests.stockfishchess.org pserve[3612]:     skip = int(self.request.matchdict["skip"])
Sep 10 13:30:25 tests.stockfishchess.org pserve[3612]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 13:30:25 tests.stockfishchess.org pserve[3612]: ValueError: invalid literal for int() with base 10: '64fd90925dab775b5359f984'
```

**Comment by ppigazzini** [comment]
Skip is the number of PGNs to be skipped before get the next 100

https://github.com/official-stockfish/fishtest/blob/4cf677de8003484e7fac4b79d892fad6a2164a2d/server/fishtest/api.py#L494-L500

https://github.com/official-stockfish/fishtest/blob/4cf677de8003484e7fac4b79d892fad6a2164a2d/server/fishtest/rundb.py#L251-L255

**Comment by vondele** [comment]
Thanks.. so that just lists the IDs.. I was assuming there was something like a bulk download per test. Not crucial.

**Comment by ppigazzini** [comment]
In the original PR https://github.com/official-stockfish/fishtest/pull/282 there was a server script to get all the PGNs using the API
https://github.com/tomtor/fishtest/blob/5f38b255bdfbbd22d12cb88823b1c3a49ea20f9a/fishtest/utils/clone_fish.py

**Comment by peregrineshahin** [comment]
> like a bulk download per test.

IMO we should introduce this instead of people having to scrap the website.

**Comment by vondele** [comment]
for reference, I was looking at the downloader script in the WDL_model repo, which indeed would benefit from bulk download api.

**Comment by vondele** [comment]
just FYI, during the bulk download there server shows quite some load 
![image](https://github.com/official-stockfish/fishtest/assets/4202567/71c97134-5f9c-4196-9ac9-3499254297a5)

if it is on the correct pserve instance, it probably doesn't matter too much.
