### ISSUE TITLE
`get_native_properties.sh` errors

### ISSUE THREAD

**Issue by MrBrain295** [official-stockfish/fishtest#1812]
I have just been getting this error recently. When I try to run fishtest (with or without sudo) I get a ton of these errors `/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied`.

**Comment by vondele** [comment]
probably related to the discussion in https://github.com/official-stockfish/fishtest/pull/1810

**Comment by ppigazzini** [comment]
I should be fixed now with the merge of https://github.com/official-stockfish/fishtest/pull/1810

**Comment by MrBrain295** [comment]
It works now thanks!
