### ISSUE TITLE
anonymized email addresses on DEV do not validate

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#1813]
The anonymized email addresses on DEV `user123@user123.user123` do not validate because `user123` is not a valid TLD. This is not so nice for testing.

```python
>>> from email_validator import validate_email
>>> validate_email("user00@user00.user00",check_deliverability=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vdbergh/.local/lib/python3.10/site-packages/email_validator/validate_email.py", line 120, in validate_email
    domain_part_info = validate_email_domain_name(domain_part, test_environment=test_environment, globally_deliverable=globally_deliverable)
  File "/home/vdbergh/.local/lib/python3.10/site-packages/email_validator/syntax.py", line 385, in validate_email_domain_name
    raise EmailSyntaxError("The part after the @-sign is not valid. It is not within a valid top-level domain.")
email_validator.exceptions_types.EmailSyntaxError: The part after the @-sign is not valid. It is not within a valid top-level domain.
>>> validate_email("user00@user00.com",check_deliverability=False)
<ValidatedEmail user00@user00.com>
>>> 
```

**Comment by ppigazzini** [comment]
I'm updating the db on DEV using my domain name `user123@user123.pigazzini.it`

**Comment by vdbergh** [comment]
It would be nice if the script for installing Fishtest made the email addresses for user00 and user01 also legal. I would not use pigazzini.it but perhaps example.com (example.com can be used freely).

**Comment by ppigazzini** [comment]
I didn't know about `example.com` status, nice suggestion!

**Comment by ppigazzini** [comment]
I updated the wiki server setup script using "example.org"

**Comment by ppigazzini** [comment]
For information, those "example" domains are rejected by the email_validator when registering a new user with the GUI.

![image](https://github.com/official-stockfish/fishtest/assets/15718418/ed43fe18-8e5c-4b9c-a98c-ce9111a1d86e)

**Comment by vdbergh** [comment]
Hmm. I guess that message is correct :) However they validate with `check_deliverability=False` which would be sufficient for database validation.
