### ISSUE TITLE
no config created

### ISSUE THREAD

**Issue by namir7666** [official-stockfish/fishtest#1824]
fishset stuck in loop 
wont create any file 

access denied by opening worker.py
![Screenshot (2)](https://github.com/official-stockfish/fishtest/assets/146670949/cc7d6df8-f694-4b7c-aed3-6e09aa292d44)
![Screenshot (3)](https://github.com/official-stockfish/fishtest/assets/146670949/c9e23de9-2342-457d-85cc-7df1a97294a5)
![Screenshot (4)](https://github.com/official-stockfish/fishtest/assets/146670949/9d9dcb5d-7bc5-47d1-8d61-0186143de131)

**Comment by vdbergh** [comment]
I propose to close this. There is not enough information to follow up.

**Comment by vondele** [comment]
ok we can reopen if more info is available.
