### ISSUE TITLE
Specifying GitHub API Key (token)

### ISSUE THREAD

**Issue by maximmasiutin** [official-stockfish/fishtest#1879]
How can I specify a GitHub API Key (token) for authenticating to the rest API from the fishtest?

I checked the source code and didn't find that option.

The way to authenticate is described here: https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28

Without authentication, when using shared IP address (NAT), GitHub gives 403 error after a small number of requests of other GitHub API clients, unless you specify a token.

Should I prepare a pull request to support the GitHub API token?

**Comment by Disservin** [comment]
The server has this, take a look at the server setup, especially the netrc part, https://github.com/official-stockfish/fishtest/wiki/Fishtest-server-setup#server-setup-1.

**Comment by maximmasiutin** [comment]
@Disservin - thank you, I am aware that the server has this option, when I set up my instance of the server. However, the client (worker) does not have this option. Still, the client connects to GitHub API. Should I submit a pull request to add this option for the client too?

**Comment by Disservin** [comment]
The client also has this https://github.com/official-stockfish/fishtest/wiki/Running-the-worker#github-api-requests-rate-limit

**Comment by maximmasiutin** [comment]
Thank you very much for your help! I apologize that I missed the fact that the client also reads this file. I configured this file on the clients and noticed immediately that `Remaining number of GitHub api calls = 5000`, whereas before I configured the token it was not 5000 but 60.
