### ISSUE TITLE
Something is wrong with https://tests.stockfishchess.org/contributors/monthly

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#1884]
See

![Screenshot from 2024-01-06 10-36-56](https://github.com/official-stockfish/fishtest/assets/6613103/fad4b591-34c1-4734-9d7d-cfad8752ab9a)

**Comment by Disservin** [comment]
Mh the contributors page it’s a different repo

**Comment by peregrineshahin** [comment]
The contributors page is loading from the patch.
Please look this test https://tests.stockfishchess.org/tests/view/654a3075136acbc57352a0ed
You used fauzi repo.

**Comment by peregrineshahin** [comment]
Loading from the cache*

**Comment by vdbergh** [comment]
I see. I think it would be better if it would just show the personal repo of the user (that's what I thought it did). There is a field for that in the userdb, but I am not sure if it is ever set.

**Comment by Disservin** [comment]
Isn’t that the last repo one specified one over the create test page ?

**Comment by vdbergh** [comment]
> Isn’t that the last repo one specified over the create test page ?

I guess that's what the code does... I most cases it will be correct I guess.

**Comment by peregrineshahin** [comment]
The correct way to me, since this field is specific to the user schema, is not do this shenanigans.

Instead the user should be asked about his repo when he registers to the website. And user should be able to change his repo from the profile page. That should reflect in the create new run page.
I will make a PR when I get the chance.

**Comment by vdbergh** [comment]
While this is certainly the correct way, it could be that users will prefer the current setup more since it doesn't require any additional actions from them.

Perhaps a compromise could be to add a button next to the repo URL saying something like "Update profile".

**Comment by peregrineshahin** [comment]
![image](https://github.com/user-attachments/assets/e5db162b-e520-4909-96c9-168701e733ae)
BTW this can be changed now in the profile :)

**Comment by vdbergh** [comment]
Thanks! I just changed it.
