### ISSUE TITLE
All of the hardy.uhassalt.be PDFs have broken links

### ISSUE THREAD

**Issue by shermansiu** [official-stockfish/fishtest#1889]
hardy.uhassalt.be no longer seems to be functional, even though going to uhassalt.be is perfectly fine. As a result, all of the PDFs on https://github.com/official-stockfish/fishtest/wiki/Fishtest-mathematics can no longer be viewed.

@vdbergh

**Comment by Disservin** [comment]
@shermansiu I have talked with Michel and he's trying to get his website up and running again. 
If you are interested in the papers you can join our discord and ask there for them.

**Comment by shermansiu** [comment]
Thanks!

**Comment by vdbergh** [comment]
Sadly I am no longer allowed to run a webserver at work that is worldwide accessible. I will try to find some alternative.

**Comment by Disservin** [comment]
> Sadly I am no longer allowed to run a webserver at work that is worldwide accessible. I will try to find some alternative.

what about hosting them on GitHub ? Alternatively have a look at Cloudflare Pages, it’s free.

**Comment by shermansiu** [comment]
Do you think you could put them up on ArXiv? I think it would be a fitting place to put them.

**Comment by vdbergh** [comment]
@Disservin Thanks for the suggestions! @shermansiu Putting them on the arxiv would somewhat confuse the people I work with in the real world :)

**Comment by vondele** [comment]
> Sadly I am no longer allowed to run a webserver at work that is worldwide accessible. I will try to find some alternative.

yet another alternative is to put them on a google drive, with access rights to viewable to the world.

**Comment by dav1312** [comment]
The last time this happened we saved them in the web archive just in case.

**Comment by shermansiu** [comment]
1. Is anyone able to post these links so that they are accessible? It's been a while since the last update.
2. Would it be okay to put these as preprints on Zenodo, alternatively? It would be preferable to find a permanent home for these links so that they can also be indexed by search engines.

**Comment by dav1312** [comment]
https://archive.org/details/fishtest_mathematics/

**Comment by shermansiu** [comment]
That's awesome, thanks!

**Comment by shermansiu** [comment]
Now that the wiki has also been updated to include the archive.org links, I'll close this issue.

**Comment by vdbergh** [comment]
I finally found time to set up a new website. https://www.cantate.be/Fishtest/

**Comment by Disservin** [comment]
amazing! :)
