### ISSUE TITLE
exited with EXIT_FAILURE

### ISSUE THREAD

**Issue by Disservin** [official-stockfish/fishtest#1897]
Btw we seem to be getting these errors from time to time...
Which is triggered by this exit (we already diagnosed this) https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L179, so it seems some nets aren't downloaded/setup correctly, since this only starts to happen after a new net test is submitted. We are also currently not exposing the uci option in stockfish since #1870 hasnt been merged.

**Comment by Disservin** [comment]
https://tests.stockfishchess.org/actions?action=&user=&text=EXIT_FAILURE

**Comment by ppigazzini** [comment]
#1870 merged.

**Comment by ppigazzini** [comment]
> https://tests.stockfishchess.org/actions?action=&user=&text=EXIT_FAILURE

From the event log, with the exception of the first two old errors, the other ones are started with the multiple nets change. The errors are stopped after the merging of the worker PR #1870
