### ISSUE TITLE
SPSA timeouts when tuning TM default move horizon

### ISSUE THREAD

**Issue by TierynnB** [official-stockfish/fishtest#1907]
When running an SPSA on the default moves horizon (mtg), many of the workers are timing out ~100% of the time. 
even at the start of the run, when the value is still very close to the default of 50.

  `// Maximum move horizon of 50 moves`
`int mtg = limits.movestogo ? std::min(limits.movestogo, 50) : 50;`

I was tuning that '50' at the end, which is the default when movestogo is not set.

first encountered here:
https://tests.stockfishchess.org/tests/view/65de6b124b19edc854ebd518

We attempted to run it at 20 +0.2 to see if that helped. it did not.
https://tests.stockfishchess.org/tests/view/65e28f01f2ef6c7333629daa

**Comment by TierynnB** [comment]
Also am getting timeouts on a spsa tune of two other variables in timeManagement.

https://tests.stockfishchess.org/tests/view/65e27ec4f2ef6c7333629cd8

**Comment by peregrineshahin** [comment]
You should not be surprised that a *time* management tune can result in time losses or else what should be in theory the tune that can even lose in time If not the TM Tune?
Second, eleminating time losses at all conditions is impossible,
Third, you are getting the actual expected results i.e. a real world result that if you tweak such values you will get, regardless of how much abused is the hardware, thus a time loss in a TM tune is in theory your patch fault.

**Comment by TierynnB** [comment]
i think its kinda surprising that less than 4000 games into it this tune
https://tests.stockfishchess.org/tests/view/65de6b124b19edc854ebd518
~65% of all games were time losses. 

the value being tuned had only moved from 50 to 46, and when i ran a four 1000 game tests for min and max values (20, 46, 64 and 70) there were no time losses.
https://tests.stockfishchess.org/tests/view/65de9dc84b19edc854ebd8ae
https://tests.stockfishchess.org/tests/view/65e27f7df2ef6c7333629ce4
https://tests.stockfishchess.org/tests/view/65e27f63f2ef6c7333629ce1
https://tests.stockfishchess.org/tests/view/65de9de14b19edc854ebd8b1
 
The test was stopped by Viren, and he told me there could be an issue with the SPSA time system, and that i could raise an issue for it.

im happy to accept these time losses if this is expected, and just let the tune do its thing.

**Comment by ppigazzini** [comment]
Testing on DEV <https://tests.stockfishchess.org/tests/view/65de6b124b19edc854ebd518> the workers are stopping with this error message:
```
Downloading https://raw.githubusercontent.com/official-stockfish/books/master/UHO_Lichess_4852_v1.epd.zip
Obtaining EvalFile of stockfish_c28b0038c81990571d7ee892c485f93ac8bd9d33 ...
Obtaining EvalFile of stockfish_c28b0038c81990571d7ee892c485f93ac8bd9d33 ...
Verifying signature of stockfish_c28b0038c81990571d7ee892c485f93ac8bd9d33 ...
Verifying signature of stockfish_c28b0038c81990571d7ee892c485f93ac8bd9d33 ...
CPU factor : 1.6252719830442364 - tc adjusted to 97.516+0.975
CPU factor : 1.6252719830442364 - tc adjusted to 1.625+0.016
CPU factor : 1.6252719830442364 - tc adjusted to 1.625+0.016
Post request https://dfts-0.pigazzini.it:443/api/request_spsa handled in 144.17ms (server: 1.90ms)
TC limit 130.02175864353893 End time: 2024-03-02 08:08:38.661854+00:00
Indexing opening suite...
  Send heartbeat for 27a429aa-ce89-42f1-a650-5849dd2da434 ... (received)
Warning: Base-c28b0038c8 doesn't have option defaultMTG

Waiting for cutechess-cli to finish ... done

Exception running games:
Cutechess-cli says: "Warning: Base-c28b0038c8 doesn't have option defaultMTG"
Informing the server
Error from remote: /api/stop_run: User user00 has too few games to stop a run
Post request https://dfts-0.pigazzini.it:443/api/stop_run handled in 129.75ms (server: 16.20ms)
Task exited
```

**Comment by TierynnB** [comment]
Yeah sorry I changed it, and I’m afk so can’t really change it back.

**Comment by ppigazzini** [comment]
No problem, testing on DEV the version with 2 variables at time control 1+0.01 and option Hash=16, at the moment no time losses, see
<https://dfts-0.pigazzini.it/tests/view/65e2e2f13cfd129d2cc54ce9>

**Comment by peregrineshahin** [comment]
Can you explain what were you trying to achieve with the extra opyiom of nodestime=600 in your tunes ?

https://tests.stockfishchess.org/tests/view/65de6b124b19edc854ebd518

**Comment by TierynnB** [comment]
I was following the wiki, [here](https://github.com/official-stockfish/fishtest/wiki/Creating-my-first-test#tuning-with-spsa:~:text=nodestime%20allows%20sf%20to%20use%20a%20budgeted%20node%20count%20management%2C%20removing%20noise%20introduced%20by%20inconsistent%20hardware).
Though maybe that wasn’t the right thing to do, reading that again.

**Comment by peregrineshahin** [comment]
Oh Oh... okay I'm trying the same settings for master in an SPRT

**Comment by peregrineshahin** [comment]
https://tests.stockfishchess.org/tests/view/65e2ebe4f2ef6c733362a212
All the games lose in time in master, It's the first time I see this in the wiki.. weird suggestion

**Comment by Disservin** [comment]
>  If using nodestime, set the time control to 160+1.6 to get the equivalent of 60+0.6 with normal TM. The nodestime games will usually finish long before the time is up, provided that the workers are able to search more nodes per milliseconds than specified in the nodestime parameter; otherwise your games will end on time.

**Comment by ppigazzini** [comment]
> Nodestime allows SF to use a budgeted node count management, removing noise introduced by inconsistent hardware speed. If the value you're tuning is not susceptible to change significantly the nps, change Test options to read Hash=128 nodestime=600. With nodestime set to 600 the workers should be able to search at least 600 nodes per milliseconds (that is 0.6 Mnps) per thread which is above the fishtest minimum (540 nodes per millisecond per thread) for a node to be considered too slow.

The information about the slow worker threshold is outdated, for SF11 fishtest has a value of 0.7 Mnps but right now is 0.208Mnps, see <https://github.com/official-stockfish/fishtest/pull/1900>

**Comment by peregrineshahin** [comment]
> The information about the slow worker threshold is outdated, for SF11 fishtest has a value of 0.7 Mnps but right now is 0.208Mnps, see https://github.com/official-stockfish/fishtest/pull/1900
Please fix the outdated wiki :P

**Comment by ppigazzini** [comment]
That is a SF internal, and that information could be added when there are not in place the practice to adjust (in a proper way) the reference nps and slow-worker nps. It could be unnecessary right now.

**Comment by ppigazzini** [comment]
@TierynnB IMO you should start your SPSA without nodestime. On DEV I'm testing your SPSA at 1+0.01 with 2 workers at 7 cores running on the same (old) CPU i7 3770k (4 cores 8 threads). No time losses.

**Comment by ppigazzini** [comment]
Resolved

**Comment by ppigazzini** [comment]
| param | value | start | min | max | c | c_end | r | r_end |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
| defaultMTG | 48.89 | 50 | 35 | 65 | 1.512 | 1.500 | 2.05e-03 | 2.00e-03 |
| advantagePercentage | 17.30 | 10 | 1 | 100 | 4.989 | 4.950 | 2.05e-03 | 2.00e-03 |
| disadvantagePercentage | 14.68 | 10 | 1 | 100 | 4.989 | 4.950 | 2.05e-03 | 2.00e-03 |

@TierynnB `cutechess-cli` accept only an integer for the parameter.
When the increment `c` is less than 1, both engines of the SPSA could play with the same parameter value, when 1 < `c` < 2, we can lose some leverage because that quantization. In case of a small value of `c`, the best practice is to multiply by 100 (at example) the values written in the "new test" page of fishtest for that parameter, and to divide by 100 in SF that value.

**Comment by TierynnB** [comment]
cool that makes sense. Do i need to multiply those values by 100 where i declare them, like this?
`int defaultMTG       = 500; //50`
`int advantagePercentage    = 100; //10`
`int disadvantagePercentage = 1000; //100`
`TUNE(SetRange(350, 650), defaultMTG);`
`TUNE(SetRange(10, 1000), advantagePercentage);`
`TUNE(SetRange(10, 1000), disadvantagePercentage);`

or can i just edit the parameter list and the above doesnt matter. just checking since ive learnt not to assume anything haha.

and yeah also divide by 100 before i use them anywhere

**Comment by ppigazzini** [comment]
I'm not a Stockfish developer, but to be sure I suggest to multiply by 100 in the declaration, copy the same raised value in the fishtest new run page, and divide by 100 before using the value in SF.

In this SPSA <https://tests.stockfishchess.org/tests/view/65def7b04b19edc854ebdec8> some parameters make no sense, at example this one:

| param | value | start | min | max | c | c_end | r | r_end |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
| g2 | 1.95 | 2 | 0 | 4 | 0.248 | 0.200 | 3.43e-03 | 2.00e-03 |

**Comment by Viren6** [comment]
@XInTheDark Make sure you are configuring your tunes to always use c values above 2 (multiplying up the base value when necessary)

**Comment by ppigazzini** [comment]
@TierynnB the parameter "disadvantagePercentage" has the starting set to the max value. This is bad because that derivative has the half the expected value
> The clipping max value, applied on parameter_value and parameter_value + ck
https://github.com/official-stockfish/fishtest/wiki/Creating-my-first-test#spsa-algorithm-in-fishtest

| param | value | start | min | max | c | c_end | r | r_end |
| -- | -- | -- | -- | -- | -- | -- | -- | -- |
| defaultMTG | 5011.22 | 5000 | 3500 | 6500 | 204.040 | 150.000 | 3.62e-03 | 2.00e-03 |
| advantagePercentage | 1546.16 | 1500 | 100 | 10000 | 673.331 | 495.000 | 3.62e-03 | 2.00e-03 |
| disadvantagePercentage | 9977.35 | 10000 | 100 | 10000 | 673.331 | 495.000 | 3.62e-03 | 2.00e-03 |

**Comment by TierynnB** [comment]
Yeah, I’d been told a couple of times to set to the default value, and in this case it’s meant to decrease maximum time allocated from 100% downwards, for this scenario. So by default it will have no impact. 

In cases like this, do you think its better to set the default to the middle of the range, to allow the tuning to converge? Or should I increase the range so my default is no longer the max, like 0 - 200. With the expectation the tuning will find anything above 100 to perform terribly anyway so it would still converge < 100.

**Comment by Viren6** [comment]
You should widen the range. The tune needs to sample that space otherwise how will it know that's bad

**Comment by ppigazzini** [comment]
> The clipping `min` and `max` must create the largest possible range of values in which the parameter makes sense. It's just a safety net because the clipping reduces the Elo sensitivity during the mini match. Set a smaller `rk` value to limit the evolution range for a parameter.
