### ISSUE TITLE
Wrong schema's causing Server crashing over long_worker_name and short_worker_name

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/fishtest#1920]
We noticed that the regexes that checks the worker names does not match the actual names of some worker, causing crashes of the server over sending time losses notification and we can no longer block workers that has the non matching name.
for example and demonstration purposes these workers is unblockable:
https://tests.stockfishchess.org/workers/SimonDemel-8cores-MacBookP
https://tests.stockfishchess.org/workers/markkulix-2cores-AMD5600G

**Comment by vdbergh** [comment]
Stupid typo 😦 . Should be 0-9a-zA-Z (alphanumeric in the worker}. I am busy now. Will submit a PR later. Unless you want to do it now…

**Comment by vdbergh** [comment]
Great point. A corrupt worker should not be allowed to crash the server!

**Comment by vdbergh** [comment]
Although now I think such a broken worker will not be able to perform any api calls. So it will be invisible to the server. Will check later.

**Comment by vdbergh** [comment]
Still the situation requires careful thought.

**Comment by vdbergh** [comment]
So I verified that worker with a non-alphanumeric name cannot connect
```
Error from remote: /api/request_task: request['worker_info']['unique_key'] (value:'?????-9c7c-40a5-98fd-606297fc3542') is not of type 'uuid'
```

The question is if there are other ways that a faulty worker name can leak into the server.

**Comment by vdbergh** [comment]
Yep. Visiting https://dfts-0.pigazzini.it/workers/okrout-28cores-_____ and blocking the corresponding worker generates an internal server error. So this should be sanitized.

**Comment by peregrineshahin** [comment]
Good news!
Btw I'm generally not a fan of shoeing web pages for non-existing users workers.. but it looks like there is no lookup for uuids in our database made before serving the page of having the ability to block a worker.. that being said this is a genera issue regarding other parts of fishtest.. serving non realistic page=1000000 with empty tests and test pages for non existing users.

**Comment by peregrineshahin** [comment]
Probably we can attiribute a bit such complain to the nature of mongodb, no relationship between tables, a worker can be blocked without even ever existing/connecting.

**Comment by vdbergh** [comment]
> Good news! Btw I'm generally not a fan of showing web pages for non-existing users workers.. but it looks like there is no lookup for uuids in our database made before serving the page of having the ability to block a worker.. that being said this is a general issue regarding other parts of fishtest.. serving non realistic page=1000000 with empty tests and test pages for non existing users.
> 
> Currently we can block workers with schema-matching names beforehand, which sounds weird.

I agree. A more natural approach would be that as soon as a worker connects its name is saved in the db, and then it becomes available for blocking unblocking. 

But some users generate new worker names frequently and this will fill the db with useless information. Hence the db would have to be pruned regularly.

Once #1916 (which reorganizes the schemas) will have been committed I can think about this.

**Comment by vdbergh** [comment]
> Probably we can attiribute a bit such complain to the nature of mongodb, no relationship between tables, a worker can be blocked without even ever existing/connecting.

Yes the choice of mongodb as a backend was a mistake I think. It should have been a relational database such as Postgress.

**Comment by peregrineshahin** [comment]
related commit https://github.com/official-stockfish/fishtest/commit/b2db262e74b3cef5b8cc20979b87cd63c1f5c789
