### ISSUE TITLE
PGNs count can be not matching results

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/fishtest#1971]
The issue is reported by @robertnurnberg 
> Some examples from https://github.com/official-stockfish/WDL_model/pull/188
Downloading 1MB .pgn.gz file with 896 games (WDL = 226 444 226) to ./pgns/24-04-29/662faee73a05f1bf7a5113c1/ ...
Download completed. The file contains 936 games. I.e. 40 more than expected.
Downloading 340MB .pgn.gz file with 464088 games (WDL = 117539 229721 116828) to ./pgns/24-04-28/662e25565e9274400985a2bf/ ...
Download completed. The file contains 332982 games. I.e. 131106 fewer than expected.
Is this expected behavior? 
(The first number comes from the meta-data at https://tests.stockfishchess.org/api/finished_runs?page=1, the second is the actual game count in the downloaded .pgn.gz)

I don't think this is an expected behavior, there is quite a mismatch between uploading pgns and sending results.. probably they are not send in the same API (which they should be) I would think that expected behavior would be to check if the results match the PGNs count at least since the PGNs should be our only source of truth for the results to be accepted IMO.
Also probably maybe the user can exit worker before PGNs are uploaded?

**Comment by peregrineshahin** [comment]
e.g.
https://tests.stockfishchess.org/tests/view/662e25565e9274400985a2bf?show_task=21 has no PGNs yet the results are accepted

**Comment by peregrineshahin** [comment]
Probably worth mentioning that also sometimes there is extra PGNs as opposed to less PGNs than expected
https://tests.stockfishchess.org/tests/view/6630386a3a05f1bf7a511b23?show_task=58
played `006 / 048` but uploadedd 19 PGNs 5 of them has are unterminated and has no results. so should it be 19-5=14?

**Comment by vondele** [comment]
> Also probably maybe the user can exit worker before PGNs are uploaded?

results are indeed communicated quite often, while pgns are uploaded once the match has finished. As a result, any non-completed batch (i.e. worker was shut down) could have no pgn associated.

Unterminated games are still saved to the pgn by cutechess, but of course can't count to the number of games played.

**Comment by peregrineshahin** [comment]
Yeah probably we consider this normal
