### ISSUE TITLE
Fishtest website is down

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/fishtest#1995]
The server returns 
```
504 Gateway Time-out
nginx/1.23.4
```
Issue since:
```
12:35 AM
Friday, May 10, 2024
Coordinated Universal Time (UTC)
```

**Comment by peregrineshahin** [comment]
Looks like it is back now

**Comment by dubslow** [comment]
Started closer to 00:15 UTC. Total downtime was nearly 4.5 hours, oz restarted the instance, ppigazinni later reported that it seemed to be due to the disk becoming full as a result of 50k cores for 2 days creating far more PGN data than accustomed to lol

**Comment by ppigazzini** [comment]
At 00:03 UTC the backup script started, dumping the collections, but the tar stopped with a file half the expected size because no space was left on the device.
