### ISSUE TITLE
wrong run_id for tests_view causes server internal error

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/fishtest#1996]
This must be a newly introduced bug... because we fixed that before.
some new code to `get_run` does not do error handling
https://tests.stockfishchess.org/tests/view/testingWithDummyString

gives 
```
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)
```

**Comment by ppigazzini** [comment]
That is not an ObjectID, testing the fix on DEV. I wonder if that should catch before by the request validation.

**Comment by ppigazzini** [comment]
The `api_schema` seems to no check if `run_id` is an `ObjectID`

https://github.com/official-stockfish/fishtest/blob/7209a4c940769023090f9b1c285397be73fd983f/server/fishtest/schemas.py#L12-L13

https://github.com/official-stockfish/fishtest/blob/7209a4c940769023090f9b1c285397be73fd983f/server/fishtest/schemas.py#L437-L457

https://github.com/official-stockfish/fishtest/blob/7209a4c940769023090f9b1c285397be73fd983f/server/fishtest/schemas.py#L505-L507
