### ISSUE TITLE
Core and machine counts displaying negative values

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/fishtest#2053]
![image](https://github.com/official-stockfish/fishtest/assets/5421953/670cb5f7-d726-4dee-a3e1-7d681e927859)
In this screen shot you can see the core count for the POnes test displayed as -265 and the machine count as (-52).

**Comment by vondele** [comment]
yes, being discussed here https://github.com/official-stockfish/fishtest/pull/2050#issuecomment-2150848138

**Comment by mstembera** [comment]
Ah thanks.
