### ISSUE TITLE
run not assigned workers

### ISSUE THREAD

**Issue by vondele** [official-stockfish/fishtest#2060]
https://tests.stockfishchess.org/tests/view/6664d56b22234461cef58e73 is no longer assigned workers (even if prio 1).

Probably this is fallout from https://github.com/official-stockfish/fishtest/pull/2049

The particular thing for this run, it had auto-purge enabled, and one worker was purged. Maybe accounting of the number of games played is not taking this correctly into account

**Comment by vondele** [comment]
also a stop and a later modify (restart) doesn't seem to help

**Comment by vdbergh** [comment]
Meanwhile Fishtest came to the same conclusion https://tests.stockfishchess.org/actions?max_actions=1&action=&user=&text=&before=1718006496.12471&run_id=

**Comment by vdbergh** [comment]
This was fixed in #2061.
