### ISSUE TITLE
Run keeps activating after Prio -1 while other tests have prio 0

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/fishtest#2063]
My test https://tests.stockfishchess.org/tests/view/66681f9e028a234afef5c492 keeps returning to active after the usual procedure of forcing the pause by doing stop -> modify to prio -1
![image](https://github.com/official-stockfish/fishtest/assets/41402573/ef30c098-9500-460e-8050-17c43ea5be4a)
https://tests.stockfishchess.org/actions?action=&user=&text=%09Extend4thread-a59e65f

**Comment by vdbergh** [comment]
I understand it. The worker has min_threads 8. 
```
uname	"Darwin 23.5.0"
architecture	
0	"64bit"
1	""
concurrency	12
max_memory	32768
min_threads	8
username	"benchislett"
version	239
python_version	
0	3
1	12
2	3
gcc_version	
0	15
1	0
2	0
compiler	"clang++"
unique_key	"320cb892..."
modified	false
ARCH	"64bit POPCNT NEON_DOTPROD"
nps	1243743
near_github_api_limit	false
remote_addr	"?.?.?.?"
country_code	"CH"
```

**Comment by peregrineshahin** [comment]
> I understand it. The worker has min_threads 8.

Let me know please, if it's expected behavior and should close.

**Comment by vondele** [comment]
yes, expected behavior, that worker is configured to only take runs that require at least 8 threads. So that -1 job is what is available and is picked.
