### ISSUE TITLE
Workers table busy wait

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#2095]
Showing the workers table seems to create a busy wait loop (Firefox CPU usage jumps) if the server is down while the main page is visible.

**Comment by peregrineshahin** [comment]
Well the server needs more than 30s to fetch the workers if the fleet join ... the problem is in the backend because the function is very inefficient,  one way to solve this is paginate the table but it doesn't explain to me why it takes sometimes 40 seconds to get.. could you please investigate...

**Comment by vdbergh** [comment]
That's a different issue. The issue I am reporting on is when the server is down. The window shows a skeleton screen forever it seems which apparently eats a lot of CPU time.
