### ISSUE TITLE
Check the possibility of deploying in the Cloudflare(worker or pages)

### ISSUE THREAD

**Issue by rti2** [official-stockfish/fishtest#2138]
I would be great to train stockfish free with Cloudflare Pages/Worker .
Please check the possibility.

**Comment by Disservin** [comment]
This doesn't make sense.
- Pages is for hosting static websites, can't run the worker 
- Workers are started over a request and then have 10 milliseconds runtime

+ it would probably violate their TOS

**Comment by rti2** [comment]
Ok thanks for your help.
Unfortunately 😕
