### ISSUE TITLE
Implement itp dependent on number of tests by user

### ISSUE THREAD

**Issue by vondele** [official-stockfish/fishtest#869]
I'm considering to implement a change to the itp calculation (see also https://github.com/official-stockfish/Stockfish/issues/3234#issuecomment-735132503):

https://github.com/glinscott/fishtest/blob/52da7b7f221e8c78089a79f02d43b4cb67528bd4/server/fishtest/rundb.py#L504-L519

basically adjusting the itp by  the number of active tests by the same user. If we call that number `Nactive` something like
``` 
if Nactive <= 2:
  itp *= 2
```
or
```
  itp /= max(1, math.pow(Nactive,1./3.))
``` 

However, I don't know how I can compute `Nactive`. @tomtor can you see how to do that easily?

**Comment by tomtor** [comment]
@vondele 

https://github.com/glinscott/fishtest/blob/52da7b7f221e8c78089a79f02d43b4cb67528bd4/server/fishtest/rundb.py#L553

Scans all runs every minute. We could calculate nactive for each user there.

**Comment by vdbergh** [comment]
This was implemented. Can be closed.
