### ISSUE TITLE
Base nps limits can be bypassed on worker side

### ISSUE THREAD

**Issue by zungur** [official-stockfish/fishtest#963]
Users can manually adjust the base nps values on the worker side to bypass minimum hardware restrictions

See: [https://github.com/glinscott/fishtest/blob/master/worker/games.py#L462](https://github.com/glinscott/fishtest/blob/master/worker/games.py#L462)

**Comment by ppigazzini** [comment]
Here you find some references that I used to learn the chi squared test:
https://github.com/glinscott/fishtest/pull/449#issuecomment-559960140

**Comment by zungur** [comment]
Other related issues #961 #796 #775 #727

**Comment by vdbergh** [comment]
Not an issue (the worker can cheat). Can be closed.

**Comment by vondele** [comment]
we do have an indication of a modified worker as well, but of course even that could be circumvented.
